"""
evaluate.py
───────────
Runs each Q&A pair from eval_dataset.json through two pipelines:
  1. Naive RAG   — single query, top-k similarity, no reranking
  2. Full pipeline — RAG-Fusion + CrossEncoder reranking (QueryExpander + Reranker)

Scores each answer with LLM-as-judge on three dimensions:
  - Faithfulness  (is the answer grounded in the retrieved chunks?)
  - Completeness  (does it fully answer the question?)
  - Relevance     (is the answer on-topic and useful?)

Outputs eval_results.json with per-question scores + pipeline averages.

Usage:
    python evaluate.py
    python evaluate.py --dataset eval_dataset.json --output eval_results.json
    python evaluate.py --limit 10   # quick smoke-test on first 10 pairs
"""

# ── Force HuggingFace offline — models already cached from ingestion ──────────
import os
os.environ["TRANSFORMERS_OFFLINE"] = "1"
os.environ["HF_DATASETS_OFFLINE"]  = "1"
os.environ["HF_HUB_OFFLINE"]       = "1"

import json
import time
import argparse
from pathlib import Path
from typing import Optional

import chromadb
import anthropic
from sentence_transformers import SentenceTransformer
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.llms import Ollama
from dotenv import load_dotenv

load_dotenv()

# ── Config ────────────────────────────────────────────────────────────────────

CHROMA_PATH     = os.getenv("CHROMA_DB_PATH",    "./chroma_db")
COLLECTION_NAME = os.getenv("CHROMA_COLLECTION", "rag_collection")
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL",   "all-MiniLM-L6-v2")
OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL",   "http://localhost:11434")
OLLAMA_MODEL    = os.getenv("OLLAMA_MODEL",      "gemma3:4b")
LLM_MODE        = os.getenv("LLM_MODE",          "local")
ANTHROPIC_KEY   = os.getenv("ANTHROPIC_API_KEY")
CLOUD_MODEL     = "claude-sonnet-4-20250514"

NAIVE_TOP_K     = 5
FULL_TOP_K      = 5
PACE_SECONDS    = 0.5
JUDGE_RETRIES   = 3

# ── Judge prompt ──────────────────────────────────────────────────────────────

JUDGE_PROMPT = """\
You are an expert evaluator for a RAG (Retrieval-Augmented Generation) system.

Score the following answer on three dimensions. Use a 1-5 integer scale.

Question: {question}

Reference Answer (ground truth from source document):
{reference_answer}

Pipeline Answer (answer generated by the RAG system):
{pipeline_answer}

Retrieved Chunks (what the system retrieved):
{retrieved_chunks}

Scoring rubric:

FAITHFULNESS (1-5): Is the pipeline answer grounded in the retrieved chunks?
  5 = Every claim is directly supported by the chunks
  4 = Almost all claims supported, minor extrapolation
  3 = Mostly supported, some unsupported claims
  2 = Several unsupported or contradicted claims
  1 = Answer is mostly hallucinated / not grounded

COMPLETENESS (1-5): Does the answer fully address the question?
  5 = Fully answers the question with appropriate detail
  4 = Mostly complete, minor gaps
  3 = Partially answers, missing key information
  2 = Superficial answer, major gaps
  1 = Does not answer the question

RELEVANCE (1-5): Is the answer on-topic and useful?
  5 = Directly answers the question, no irrelevant content
  4 = Mostly relevant, minor tangents
  3 = Somewhat relevant but unfocused
  2 = Largely off-topic
  1 = Completely irrelevant

Respond ONLY with valid JSON, no preamble, no markdown:
{{"faithfulness": <int 1-5>, "completeness": <int 1-5>, "relevance": <int 1-5>, "reasoning": "<one sentence>"}}
"""

# ── Naive RAG ─────────────────────────────────────────────────────────────────

class NaiveRAG:
    """Single query, top-k similarity, no reranking."""

    def __init__(self, collection, embedder: SentenceTransformer, top_k: int = NAIVE_TOP_K):
        self.collection = collection
        self.embedder   = embedder
        self.top_k      = top_k

    def retrieve(self, question: str) -> list[dict]:
        embedding = self.embedder.encode(question).tolist()
        results   = self.collection.query(
            query_embeddings=[embedding],
            n_results=self.top_k,
            include=["documents", "metadatas"],
        )
        return [
            {"content": doc, "source": meta.get("source", "unknown"), "page": meta.get("page", "?")}
            for doc, meta in zip(results["documents"][0], results["metadatas"][0])
        ]

    def answer(self, question: str, llm_fn) -> dict:
        chunks  = self.retrieve(question)
        context = "\n\n---\n\n".join(c["content"] for c in chunks)
        prompt  = f"Answer the following question using only the provided context.\n\nContext:\n{context}\n\nQuestion: {question}\n\nAnswer:"
        return {"answer": llm_fn(prompt), "sources": chunks}


# ── Full pipeline ─────────────────────────────────────────────────────────────

class FullPipeline:
    """
    RAG-Fusion + CrossEncoder reranking.
    Uses your existing QueryExpander and Reranker classes directly.
    """

    def __init__(self, chroma_path: str, collection_name: str, ollama_base_url: str, ollama_model: str, top_k: int = FULL_TOP_K):
        from query_expander import QueryExpander
        from reranker import Reranker

        self.top_k = top_k

        # Ollama LLM for query expansion only
        self.llm = Ollama(base_url=ollama_base_url, model=ollama_model)

        # LangChain HuggingFace embeddings wrapping the cached model
        lc_embeddings = HuggingFaceEmbeddings(
            model_name=EMBEDDING_MODEL,
            model_kwargs={"device": "cpu"},
            encode_kwargs={"normalize_embeddings": True},
        )

        # LangChain Chroma wrapping the existing ChromaDB
        self.vectorstore = Chroma(
            collection_name=collection_name,
            persist_directory=chroma_path,
            embedding_function=lc_embeddings,
        )

        self.expander = QueryExpander(llm=self.llm, vectorstore=self.vectorstore)
        self.reranker = Reranker()

    def retrieve(self, question: str) -> list[dict]:
        # QueryExpander.retrieve() returns LangChain Document objects
        docs = self.expander.retrieve(question, k=10, top_n=self.top_k * 2)

        # Reranker.rerank() takes and returns Document objects
        reranked = self.reranker.rerank(question, docs, top_k=self.top_k)

        # Convert to plain dicts for our eval framework
        return [
            {"content": doc.page_content, "source": doc.metadata.get("source", "unknown"), "page": doc.metadata.get("page", "?")}
            for doc in reranked
        ]

    def answer(self, question: str, llm_fn) -> dict:
        chunks  = self.retrieve(question)
        context = "\n\n---\n\n".join(c["content"] for c in chunks)
        prompt  = f"Answer the following question using only the provided context.\n\nContext:\n{context}\n\nQuestion: {question}\n\nAnswer:"
        return {"answer": llm_fn(prompt), "sources": chunks}


# ── LLM caller ────────────────────────────────────────────────────────────────

def make_llm_fn(mode: str, anthropic_client: Optional[anthropic.Anthropic]):
    if mode == "cloud":
        def cloud_llm(prompt: str) -> str:
            r = anthropic_client.messages.create(
                model=CLOUD_MODEL, max_tokens=512,
                messages=[{"role": "user", "content": prompt}],
            )
            return r.content[0].text.strip()
        return cloud_llm
    else:
        import httpx
        def local_llm(prompt: str) -> str:
            r = httpx.post(
                f"{OLLAMA_BASE_URL}/api/generate",
                json={"model": OLLAMA_MODEL, "prompt": prompt, "stream": False},
                timeout=120,
            )
            r.raise_for_status()
            return r.json()["response"].strip()
        return local_llm


# ── LLM-as-judge ─────────────────────────────────────────────────────────────

def judge_answer(anthropic_client, question, reference_answer, pipeline_answer, retrieved_chunks, retries=JUDGE_RETRIES):
    chunks_text = "\n\n---\n\n".join(
        f"[Source: {c.get('source','?')} p.{c.get('page','?')}]\n{c.get('content','')}"
        for c in retrieved_chunks[:5]
    )
    prompt = JUDGE_PROMPT.format(
        question=question, reference_answer=reference_answer,
        pipeline_answer=pipeline_answer, retrieved_chunks=chunks_text,
    )
    for attempt in range(retries):
        try:
            response = anthropic_client.messages.create(
                model=CLOUD_MODEL, max_tokens=256,
                messages=[{"role": "user", "content": prompt}],
            )
            raw = response.content[0].text.strip()
            if raw.startswith("```"):
                raw = raw.split("```")[1]
                if raw.startswith("json"):
                    raw = raw[4:]
            parsed = json.loads(raw)
            for key in ("faithfulness", "completeness", "relevance"):
                val = parsed.get(key)
                if not isinstance(val, int) or not (1 <= val <= 5):
                    raise ValueError(f"Invalid score for {key}: {val}")
            return {
                "faithfulness": parsed["faithfulness"],
                "completeness": parsed["completeness"],
                "relevance":    parsed["relevance"],
                "reasoning":    parsed.get("reasoning", ""),
                "overall":      round((parsed["faithfulness"] + parsed["completeness"] + parsed["relevance"]) / 3, 2),
            }
        except (json.JSONDecodeError, ValueError, KeyError) as e:
            if attempt < retries - 1:
                time.sleep(1)
                continue
            print(f"    [!] Judge parse error: {e}")
            return None
        except anthropic.RateLimitError:
            wait = 5 * (attempt + 1)
            print(f"    [!] Rate limit — waiting {wait}s...")
            time.sleep(wait)
    return None


# ── Aggregation ───────────────────────────────────────────────────────────────

def aggregate_scores(results, pipeline_key):
    scores = [r[pipeline_key]["scores"] for r in results if r.get(pipeline_key, {}).get("scores")]
    if not scores:
        return {}
    n = len(scores)
    return {
        "n":            n,
        "faithfulness": round(sum(s["faithfulness"] for s in scores) / n, 2),
        "completeness": round(sum(s["completeness"] for s in scores) / n, 2),
        "relevance":    round(sum(s["relevance"]    for s in scores) / n, 2),
        "overall":      round(sum(s["overall"]      for s in scores) / n, 2),
    }


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset",     type=str, default="eval_dataset.json")
    parser.add_argument("--output",      type=str, default="eval_results.json")
    parser.add_argument("--chroma_path", type=str, default=CHROMA_PATH)
    parser.add_argument("--collection",  type=str, default=COLLECTION_NAME)
    parser.add_argument("--limit",       type=int, default=None)
    parser.add_argument("--pipeline",    type=str, default="both", choices=["naive", "full", "both"])
    args = parser.parse_args()

    dataset_path = Path(args.dataset)
    if not dataset_path.exists():
        raise FileNotFoundError(f"Dataset not found: {dataset_path} — run dataloader.py first")

    dataset = json.loads(dataset_path.read_text())
    if args.limit:
        dataset = dataset[:args.limit]
    print(f"[evaluate] Loaded {len(dataset)} Q&A pairs")

    if not ANTHROPIC_KEY:
        raise RuntimeError("ANTHROPIC_API_KEY not set")

    anthropic_client = anthropic.Anthropic(api_key=ANTHROPIC_KEY)
    llm_fn           = make_llm_fn(LLM_MODE, anthropic_client)

    print(f"[evaluate] Loading embedder: {EMBEDDING_MODEL}")
    embedder = SentenceTransformer(EMBEDDING_MODEL)

    chroma = chromadb.PersistentClient(path=args.chroma_path)
    try:
        collection = chroma.get_collection(args.collection)
    except Exception:
        collections = chroma.list_collections()
        collection  = chroma.get_collection(collections[0].name)
        print(f"[evaluate] Using collection: {collection.name}")

    naive_rag     = NaiveRAG(collection, embedder)
    full_pipeline = None

    if args.pipeline in ("full", "both"):
        try:
            full_pipeline = FullPipeline(
                chroma_path=args.chroma_path,
                collection_name=collection.name,
                ollama_base_url=OLLAMA_BASE_URL,
                ollama_model=OLLAMA_MODEL,
            )
            print("[evaluate] Full pipeline ready")
        except Exception as e:
            print(f"[!] Full pipeline failed to load: {e}")
            if args.pipeline == "full":
                raise
            args.pipeline = "naive"

    results = []
    print(f"\n[evaluate] Running — {len(dataset)} pairs, pipeline={args.pipeline}\n")

    for i, pair in enumerate(dataset):
        q, ref = pair["question"], pair["reference_answer"]
        print(f"  [{i+1:>3}/{len(dataset)}] {q[:75]}{'...' if len(q) > 75 else ''}")

        result = {
            "pair_id":          pair.get("pair_id", i + 1),
            "question":         q,
            "reference_answer": ref,
            "source_doc":       pair.get("source_doc"),
            "source_page":      pair.get("source_page"),
        }

        if args.pipeline in ("naive", "both"):
            print("    → naive...", end=" ", flush=True)
            out    = naive_rag.answer(q, llm_fn)
            scores = judge_answer(anthropic_client, q, ref, out["answer"], out["sources"])
            result["naive"] = {"answer": out["answer"], "sources": out["sources"], "scores": scores}
            print(f"F={scores['faithfulness']} C={scores['completeness']} R={scores['relevance']}" if scores else "scoring failed")

        if args.pipeline in ("full", "both") and full_pipeline:
            print("    → full...", end=" ", flush=True)
            out    = full_pipeline.answer(q, llm_fn)
            scores = judge_answer(anthropic_client, q, ref, out["answer"], out["sources"])
            result["full"] = {"answer": out["answer"], "sources": out["sources"], "scores": scores}
            print(f"F={scores['faithfulness']} C={scores['completeness']} R={scores['relevance']}" if scores else "scoring failed")

        results.append(result)
        time.sleep(PACE_SECONDS)

    summary = {"n_pairs": len(results)}
    if args.pipeline in ("naive", "both"):
        summary["naive"] = aggregate_scores(results, "naive")
    if args.pipeline in ("full", "both") and full_pipeline:
        summary["full"]  = aggregate_scores(results, "full")
    if "naive" in summary and "full" in summary:
        n, f = summary["naive"], summary["full"]
        summary["delta"] = {k: round(f[k] - n[k], 2) for k in ("faithfulness", "completeness", "relevance", "overall")}

    Path(args.output).write_text(json.dumps({"summary": summary, "results": results}, indent=2, ensure_ascii=False))
    print(f"\n[evaluate] Saved → {args.output}")

    print("\n── Results ──────────────────────────────────────────────────────────")
    print(f"{'Pipeline':<16} {'Faithfulness':>13} {'Completeness':>13} {'Relevance':>10} {'Overall':>8}  {'N':>4}")
    print("─" * 70)
    for key, label in [("naive", "Naive RAG"), ("full", "Full Pipeline")]:
        if key in summary and summary[key]:
            s = summary[key]
            print(f"{label:<16} {s['faithfulness']:>13.2f} {s['completeness']:>13.2f} {s['relevance']:>10.2f} {s['overall']:>8.2f}  {s['n']:>4}")
    if "delta" in summary:
        d    = summary["delta"]
        sign = lambda v: f"+{v:.2f}" if v >= 0 else f"{v:.2f}"
        print("─" * 70)
        print(f"{'Delta':<16} {sign(d['faithfulness']):>13} {sign(d['completeness']):>13} {sign(d['relevance']):>10} {sign(d['overall']):>8}")
    print()


if __name__ == "__main__":
    main()